---
  name: Build and Run C Program

  on:
    pull_request:
      branches:
        - main

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install GCC
          run: |
            sudo apt-get update
            sudo apt-get install -y gcc

        - name: Compile C program
          run: gcc hello.c -o hello

        - name: Run C program
          run: ./hello

